int A=880;
int B=988;
int C=523;
int D=587;
int E=659;
int F=698;
int G=784;
int wholenote = 2000;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(E,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkBlue;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(D+35,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkCyan;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(E,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkBlue;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(D+35,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkCyan;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(E,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkBlue;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(B/2,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkGray;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(D-17,wholenote/4);
Console.BackgroundColor=ConsoleColor.Cyan;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(C,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkCyan;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(A,wholenote);
Console.BackgroundColor=ConsoleColor.DarkBlue;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(C,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkCyan;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(E,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkBlue;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(A,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkCyan;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(B,wholenote);
Console.BackgroundColor=ConsoleColor.DarkBlue;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(E,wholenote/2);
Console.BackgroundColor=ConsoleColor.DarkCyan;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(A,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkBlue;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(B,wholenote/2);
Console.BackgroundColor=ConsoleColor.DarkCyan;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(C,wholenote);
Console.BackgroundColor=ConsoleColor.DarkBlue;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(E/2,wholenote/2);
Console.BackgroundColor=ConsoleColor.DarkCyan;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(E,wholenote/2);
Console.BackgroundColor=ConsoleColor.DarkBlue;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(D+35,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkCyan;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(E,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkBlue;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(D-17,wholenote/4);
Console.BackgroundColor=ConsoleColor.Cyan;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(E,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkCyan;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(B/2,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkBlue;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(D,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkCyan;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(D+35,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkBlue;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(C,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkCyan;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(A,wholenote);
Console.BackgroundColor=ConsoleColor.DarkBlue;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(C/2,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkCyan;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(E/2,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkBlue;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(A,wholenote/4);
Console.BackgroundColor=ConsoleColor.DarkCyan;
Console.Clear();
Console.WriteLine("Fur Elise on my computer");
Console.Beep(B,wholenote);






